
var apModalsHtml = '<div class="modal animated bounceIn" id="CustomAlertModal" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">X</span></button><h4 class="modal-title">Alert</h4></div><div class="modal-body"></div><div class="modal-footer"><button type="button" class="okbtn btn btn-default " data-dismiss="modal">OK</button></div></div></div></div>';
apModalsHtml += '<div class="modal animated jackInTheBox" id="APCustomModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">X</span></button><h4 class="modal-title">Alert</h4></div><div class="modal-body"><div class="ap-modal-body"></div><div class="clearfix"></div><div class="text-center"><button type="button" class="btn btn-primary ap-modal-body-btn" data-dismiss="modal">Continue</button></div><div class="clearfix"></div></div><div class="modal-footer"><button type="button" class="ap-modal-left-btn btn btn-default pull-left" data-dismiss="modal">Close</button><button type="button" class="ap-modal-right-btn1 btn btn-default" data-dismiss="modal">OK</button><button type="button" class="ap-modal-right-btn2 btn btn-default " data-dismiss="modal">Cancel</button></div></div></div></div>';
apModalsHtml += '<div class="modal animated bounceIn" id="CustomConfirmModal" tabindex="-1" role="dialog" data-keyboard="false"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><h4 class="modal-title">Confirm</h4></div><div class="modal-body"></div><div class="modal-footer"><button type="button" class="okbtn btn btn-default" data-dismiss="modal">OK</button><button type="button" class="cancelbtn btn btn-default " data-dismiss="modal">Cancel</button></div></div></div></div>';
document.body.innerHTML += apModalsHtml; var apModalsCss = '#CustomAlertModal{z-index:1052;}.modal-header{color: #fff;padding: 9px 15px;border-bottom: 1px solid #eee;}'; apModalsCss += '.modal-header-danger{background-color: #d9534f;}.modal-header-success{background-color: #5cb85c;}.modal-header-primary{background-color: #286090;}.modal-header-info{background-color: #31b0d5;}.modal-header-warning{background-color: #f0ad4e;}'; apModalsCss += '.modal-ul { list-style-type:square;  padding:15px; margin-left:30px;}.modal-ul>li{ font-size:17px; line-height:28px;}.modal .btn{border-radius: 0 !important;}.modal-main-text {font-size: 18px;}'; var apModalCssElement = document.createElement('style'); apModalCssElement.setAttribute('type', 'text/css'); apModalCssElement.innerHTML = apModalsCss; document.body.appendChild(apModalCssElement); var ModalOkCallback = null; function CustomAlertModal(title, headerClass, body, OkCallback) {
    $('#CustomAlertModal').find('.modal-header').addClass('modal-header-' + headerClass); $('#CustomAlertModal').find('.modal-title').html(title); $('#CustomAlertModal').find('.modal-body').html(body); $('#CustomAlertModal .modal-footer .okbtn').attr('class', 'okbtn btn btn-' + headerClass); $('#CustomAlertModal').modal('show'); if (OkCallback) { ModalOkCallback = OkCallback; }
else
ModalOkCallback=null;}
function CustomConfirmModal(title,headerClass,body,OkCallback,CancelCallback){$('#CustomConfirmModal').find('.modal-header').addClass('modal-header-'+ headerClass);$('#CustomConfirmModal').find('.modal-title').html(title);$('#CustomConfirmModal').find('.modal-body').html(body);$('#CustomConfirmModal .modal-footer .okbtn').attr('class','okbtn btn btn-'+ headerClass);$('#CustomConfirmModal').modal('show');if(OkCallback){$('#CustomConfirmModal .modal-footer .okbtn').off('click').click(function(){OkCallback();});}
if(CancelCallback){$('#CustomConfirmModal .modal-footer .cancelbtn').off('click').click(function(){CancelCallback();});}}
function CustomAlertModalWithCustomBtn(title,headerClass,body,btnText,OkCallback){$('#CustomAlertModal').find('.modal-header').addClass('modal-header-'+ headerClass);$('#CustomAlertModal').find('.modal-title').html(title);$('#CustomAlertModal').find('.modal-body').html(body);$('#CustomAlertModal .modal-footer .okbtn').text(btnText?btnText:'OK');$('#CustomAlertModal .modal-footer .okbtn').attr('class','okbtn btn btn-'+ headerClass);$('#CustomAlertModal').modal('show');if(OkCallback){ModalOkCallback=OkCallback;}
else
ModalOkCallback=null;}
function CustomConfirmModalWithCustomBtns(title,headerClass,body,okBtn,cancelBtn,OkCallback,CancelCallback){$('#CustomConfirmModal').find('.modal-header').addClass('modal-header-'+ headerClass);$('#CustomConfirmModal').find('.modal-title').html(title);$('#CustomConfirmModal').find('.modal-body').html(body);$('#CustomConfirmModal .modal-footer .okbtn').text(okBtn?okBtn:'OK');$('#CustomConfirmModal .modal-footer .cancelbtn').text(cancelBtn?cancelBtn:'Cancel');$('#CustomConfirmModal .modal-footer .okbtn').attr('class','okbtn btn btn-'+ headerClass);$('#CustomConfirmModal').modal('show');if(OkCallback){$('#CustomConfirmModal .modal-footer .okbtn').off('click').click(function(){OkCallback();});}
if(CancelCallback){$('#CustomConfirmModal .modal-footer .cancelbtn').off('click').click(function(){CancelCallback();});}}
var APCustomModalCloseCallback=null;function APCustomModal(obj){var objAllOptions={title:'Alert',headerClass:'warning',body:'',bodyBtn:'',bodyBtnClass:'',bodyBtnCallback:undefined,leftBtn:'',leftBtnClass:'',leftBtnCallback:undefined,rightBtn1:'',rightBtn1Class:'',rightBtn1Callback:undefined,rightBtn2:'',rightBtn2Class:'',rightBtn2Callback:undefined,hideCloseIcon:false,escClose:false,outsideClickClose:false,modalCloseCallback:undefined};try{if(obj.modalCloseCallback){APCustomModalCloseCallback=obj.modalCloseCallback;}
$('#APCustomModal').find('.modal-header').addClass('modal-header-'+ obj.headerClass);$('#APCustomModal').find('.modal-title').html(obj.title);$('#APCustomModal').find('.ap-modal-body').html(obj.body);var topCloseBtn=$('#APCustomModal .modal-header').find('.close');if(obj.hideCloseIcon&&topCloseBtn.length>0){topCloseBtn.hide();}
var bodyBtn=$('#APCustomModal').find('.ap-modal-body-btn');var leftBtn=$('#APCustomModal').find('.ap-modal-left-btn');var rightBtn1=$('#APCustomModal').find('.ap-modal-right-btn1');var rightBtn2=$('#APCustomModal').find('.ap-modal-right-btn2');if(!obj.bodyBtn){bodyBtn.hide();}
else{bodyBtn.text(obj.bodyBtn).attr('class','ap-modal-body-btn btn btn-'+(obj.bodyBtnClass?obj.bodyBtnClass:'primary')).show();if(obj.bodyBtnCallback){bodyBtn.off('click').click(function(){obj.bodyBtnCallback();});}}
if(!obj.leftBtn){leftBtn.hide();}
else{leftBtn.text(obj.leftBtn).attr('class','ap-modal-left-btn pull-left btn btn-'+(obj.leftBtnClass?obj.leftBtnClass:'primary')).show();if(obj.leftBtnCallback){leftBtn.off('click').click(function(){obj.leftBtnCallback();});}}
if(!obj.rightBtn1){rightBtn1.hide();}
else{rightBtn1.text(obj.rightBtn1).attr('class','ap-modal-right-btn1 btn btn-'+(obj.rightBtn1Class?obj.rightBtn1Class:'primary')).show();if(obj.rightBtn1Callback){rightBtn1.off('click').click(function(){obj.rightBtn1Callback();});}}
if(!obj.rightBtn2){rightBtn2.hide();}
else{rightBtn2.text(obj.rightBtn2).attr('class','ap-modal-right-btn2 btn btn-'+(obj.rightBtn2Class?obj.rightBtn2Class:'primary')).show();if(obj.rightBtn2Callback){rightBtn2.off('click').click(function(){obj.rightBtn2Callback();});}}
if(obj.escClose){$('#APCustomModal').removeData('keyboard').removeAttr('data-keyboard');}
if(obj.outsideClickClose){$('#APCustomModal').removeData('backdrop').removeAttr('data-backdrop');}
$('#APCustomModal').modal('show');}
catch(ex){console.info('APCustomModal Show Exception : '+ ex);}}
$(function(){$('#CustomAlertModal').on('hide.bs.modal',function(e){$('#CustomAlertModal').find('.modal-header').attr('class','modal-header');$('#CustomAlertModal').find('.modal-title').html('Custom Alert');$('#CustomAlertModal').find('.modal-body').html('');$('#CustomAlertModal .modal-footer .okbtn').attr('class','okbtn btn btn-default');$('#CustomAlertModal .modal-footer .okbtn').off("click");if(ModalOkCallback!=null){ModalOkCallback();ModalOkCallback=null;}});$('#CustomConfirmModal').on('hide.bs.modal',function(e){$('#CustomConfirmModal').find('.modal-header').attr('class','modal-header');$('#CustomConfirmModal').find('.modal-title').html('Custom Confirm');$('#CustomConfirmModal').find('.modal-body').html('');$('#CustomConfirmModal .modal-footer .okbtn').text('OK').attr('class','okbtn btn btn-default');$('#CustomConfirmModal .modal-footer .cancelbtn').text('Cancel');$('#CustomConfirmModal .modal-footer .okbtn').off("click");});$('#APCustomModal').on('hide.bs.modal',function(e){try{$('#APCustomModal').find('.modal-header').attr('class','modal-header');$('#APCustomModal').find('.modal-title').html('Alert');$('#APCustomModal').find('.ap-modal-body').html('');var bodyBtn=$('#APCustomModal').find('.ap-modal-body-btn');var leftBtn=$('#APCustomModal').find('.ap-modal-left-btn');var rightBtn1=$('#APCustomModal').find('.ap-modal-right-btn1');var rightBtn2=$('#APCustomModal').find('.ap-modal-right-btn2');bodyBtn.off('click').text('').attr('class','ap-modal-body-btn btn btn-default').hide();leftBtn.off('click').text('').attr('class','ap-modal-left-btn pull-left btn btn-default').hide();rightBtn1.off('click').text('').attr('class','ap-modal-right-btn1 btn btn-default').hide();rightBtn2.off('click').text('').attr('class','ap-modal-right-btn2 btn btn-default').hide();$('#APCustomModal').data('keyboard','false').attr('data-keyboard','false');$('#APCustomModal').data('backdrop','static').attr('data-backdrop','static');if(APCustomModalCloseCallback!=null){APCustomModalCloseCallback();APCustomModalCloseCallback=null;}}
    catch (ex) { console.info('APCustomModal Hide Exception : ' + ex); }
});
});
$(function () {
    $(document).on('show.bs.modal', '.modal', function (event) {
        var zIndex = 1040 + (10 * $('.modal:visible').length);
        $(this).css('z-index', zIndex);
        setTimeout(function () {
            $('.modal-backdrop').not('.modal-stack').css('z-index', zIndex - 1).addClass('modal-stack');
        }, 0);
    });
});